---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    database: postgres
spec:
  ports:
    - port: 5432
      name: postgres-port
  selector:
    database: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-svc
  replicas: 2
  selector:
    matchLabels:
      database: postgres
  template:
    metadata:
      labels:
        database: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.3-bullseye
          ports:
            - containerPort: 5432
              name: database-port
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data/pgdata
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
