services:
  database:
    image: postgres:15.3
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: app_distributor
      POSTGRES_DB: uet_app_distributor
