services:
  database:
    image: postgres:15.3
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: distributor
      POSTGRES_USER: distributor
      POSTGRES_DB: uet_app_distributor
