apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: uad-postgres-cluster
  namespace: uet-app-distributor
spec:
  teamId: "acid"
  patroni:
    pg_hba:
      - local     all          all                        trust
      - hostssl   all          +zalandos 127.0.0.1/32     pam
      - host      all          all       127.0.0.1/32     md5
      - hostssl   all          +zalandos ::1/128          pam
      - host      all          all       ::1/128          md5
      - local     replication  standby                    trust
      - hostssl   replication  standby   all              md5
      # - hostnossl all          all       all              reject
      - hostssl   all          +zalandos all              pam
      - hostssl   all          all       all              md5
      - host      all          all       10.1.0.0/16      md5
  volume:
    storageClass: nfs
    size: 10Gi
  numberOfInstances: 2
  users:
    distributor: # database owner
      - superuser
      - createdb
    sample_app_user: [] # role for application sample_app
  databases:
    uet_app_distributor: distributor # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "15"
